/* Generated By:JavaCC: Do not edit this line. CalculadoraConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculadoraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AP = 4;
  /** RegularExpression Id. */
  int FP = 5;
  /** RegularExpression Id. */
  int SINAL = 6;
  /** RegularExpression Id. */
  int PONTO = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int DIGITO = 9;
  /** RegularExpression Id. */
  int OP = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"(\"",
    "\")\"",
    "<SINAL>",
    "\".\"",
    "<NUM>",
    "<DIGITO>",
    "<OP>",
  };

}
