/* Generated By:JavaCC: Do not edit this line. CalculaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 1;
  /** RegularExpression Id. */
  int LETRA = 2;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int F = 4;
  /** RegularExpression Id. */
  int AD = 5;
  /** RegularExpression Id. */
  int MUL = 6;
  /** RegularExpression Id. */
  int OP1 = 7;
  /** RegularExpression Id. */
  int OP2 = 8;
  /** RegularExpression Id. */
  int NUM = 9;
  /** RegularExpression Id. */
  int DIGITO = 10;
  /** RegularExpression Id. */
  int PONTO = 11;
  /** RegularExpression Id. */
  int ATRIB = 12;
  /** RegularExpression Id. */
  int NOVALINHA = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "\"(\"",
    "\")\"",
    "<AD>",
    "<MUL>",
    "\"^\"",
    "\"#\"",
    "<NUM>",
    "<DIGITO>",
    "\".\"",
    "\"=\"",
    "\"\\n\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
