/* Generated By:JavaCC: Do not edit this line. ConjuntoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConjuntoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int LETRAS = 5;
  /** RegularExpression Id. */
  int PALAVRAS = 6;
  /** RegularExpression Id. */
  int RT = 7;
  /** RegularExpression Id. */
  int AC = 8;
  /** RegularExpression Id. */
  int FC = 9;
  /** RegularExpression Id. */
  int PV = 10;
  /** RegularExpression Id. */
  int OP = 11;
  /** RegularExpression Id. */
  int UND = 12;
  /** RegularExpression Id. */
  int IGUAL = 13;
  /** RegularExpression Id. */
  int VIRG = 14;
  /** RegularExpression Id. */
  int AP = 15;
  /** RegularExpression Id. */
  int FP = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<NUM>",
    "<LETRAS>",
    "<PALAVRAS>",
    "\"...\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "<OP>",
    "\"_\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
