/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int B = 2;
  /** RegularExpression Id. */
  int S = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<A>",
    "\".\"",
    "<S>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
