/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELACIONAIS = 1;
  /** RegularExpression Id. */
  int BOOL_A = 2;
  /** RegularExpression Id. */
  int NEGACAO = 3;
  /** RegularExpression Id. */
  int BOOL_B = 4;
  /** RegularExpression Id. */
  int SENTENCA_BOOLEANA = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int THEN = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int REPEAT = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int UNTIL = 13;
  /** RegularExpression Id. */
  int INICIO = 14;
  /** RegularExpression Id. */
  int FIM = 15;
  /** RegularExpression Id. */
  int TIPO = 16;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 17;
  /** RegularExpression Id. */
  int PALAVRA = 18;
  /** RegularExpression Id. */
  int LETRA = 19;
  /** RegularExpression Id. */
  int NUM = 20;
  /** RegularExpression Id. */
  int DIGITO = 21;
  /** RegularExpression Id. */
  int SINAL = 22;
  /** RegularExpression Id. */
  int PONTO = 23;
  /** RegularExpression Id. */
  int ATRIB = 24;
  /** RegularExpression Id. */
  int ATRIBTERNARIO = 25;
  /** RegularExpression Id. */
  int PERGTERNARIO = 26;
  /** RegularExpression Id. */
  int DP = 27;
  /** RegularExpression Id. */
  int PV = 28;
  /** RegularExpression Id. */
  int AP = 29;
  /** RegularExpression Id. */
  int FP = 30;
  /** RegularExpression Id. */
  int AC = 31;
  /** RegularExpression Id. */
  int FC = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<RELACIONAIS>",
    "<BOOL_A>",
    "\"~\"",
    "<BOOL_B>",
    "<SENTENCA_BOOLEANA>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\"do\"",
    "\"for\"",
    "\"until\"",
    "\"$BEGIN_PROGRAM\"",
    "\"$END_PROGRAM\"",
    "<TIPO>",
    "<IDENTIFICADOR>",
    "<PALAVRA>",
    "<LETRA>",
    "<NUM>",
    "<DIGITO>",
    "<SINAL>",
    "\".\"",
    "\"=\"",
    "\":=\"",
    "\"?\"",
    "\":\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
