/* Generated By:JavaCC: Do not edit this line. BooleanoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BooleanoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONST = 4;
  /** RegularExpression Id. */
  int AP = 5;
  /** RegularExpression Id. */
  int FP = 6;
  /** RegularExpression Id. */
  int SINAL = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<CONST>",
    "\"(\"",
    "\")\"",
    "<SINAL>",
  };

}
